// Copyright (c) 2026 Lark Technologies Pte. Ltd.
// SPDX-License-Identifier: MIT

package base

import "github.com/larksuite/cli/shortcuts/common"

// Shortcuts returns all base shortcuts.
func Shortcuts() []common.Shortcut {
	return []common.Shortcut{
		BaseTableList,
		BaseTableGet,
		BaseTableCreate,
		BaseTableUpdate,
		BaseTableDelete,
		BaseFieldList,
		BaseFieldGet,
		BaseFieldCreate,
		BaseFieldUpdate,
		BaseFieldDelete,
		BaseFieldSearchOptions,
		BaseViewList,
		BaseViewGet,
		BaseViewCreate,
		BaseViewDelete,
		BaseViewGetFilter,
		BaseViewSetFilter,
		BaseViewGetGroup,
		BaseViewSetGroup,
		BaseViewGetSort,
		BaseViewSetSort,
		BaseViewGetTimebar,
		BaseViewSetTimebar,
		BaseViewGetCard,
		BaseViewSetCard,
		BaseViewRename,
		BaseRecordList,
		BaseRecordGet,
		BaseRecordUpsert,
		BaseRecordUploadAttachment,
		BaseRecordDelete,
		BaseRecordHistoryList,
		BaseBaseGet,
		BaseBaseCopy,
		BaseBaseCreate,
		BaseRoleCreate,
		BaseRoleDelete,
		BaseRoleUpdate,
		BaseRoleList,
		BaseRoleGet,
		BaseAdvpermEnable,
		BaseAdvpermDisable,
		BaseWorkflowList,
		BaseWorkflowGet,
		BaseWorkflowCreate,
		BaseWorkflowUpdate,
		BaseWorkflowEnable,
		BaseWorkflowDisable,
		BaseDataQuery,
		BaseFormCreate,
		BaseFormDelete,
		BaseFormsList,
		BaseFormUpdate,
		BaseFormGet,
		BaseFormQuestionsCreate,
		BaseFormQuestionsDelete,
		BaseFormQuestionsUpdate,
		BaseFormQuestionsList,
		BaseDashboardList,
		BaseDashboardGet,
		BaseDashboardCreate,
		BaseDashboardUpdate,
		BaseDashboardDelete,
		BaseDashboardBlockList,
		BaseDashboardBlockGet,
		BaseDashboardBlockCreate,
		BaseDashboardBlockUpdate,
		BaseDashboardBlockDelete,
	}
}
