// Copyright (c) 2026 Lark Technologies Pte. Ltd.
// SPDX-License-Identifier: MIT

package draft

import (
	"regexp"
	"strings"
)

// QuoteWrapperClass is the CSS class name used by Lark's mail composer
// for reply/forward quote blocks. Both +reply and +forward wrap the
// quoted original message in a <div> with this class.
// Exported so that mail_quote.go (the generator) and projection.go
// (the detector) share a single source of truth.
const QuoteWrapperClass = "history-quote-wrapper"

// quoteWrapperRe matches an actual <div> element whose class attribute
// contains QuoteWrapperClass. This avoids false positives when the
// string appears as plain text, inside <pre> blocks, or in
// HTML-escaped content.
//
// Matches:
//   - <div class="history-quote-wrapper">           (reply)
//   - <div id="..." class="history-quote-wrapper">  (forward)
var quoteWrapperRe = regexp.MustCompile(`<div\s[^>]*class="[^"]*` + QuoteWrapperClass + `[^"]*"`)

var cidRefRegexp = regexp.MustCompile(`(?i)cid:([^"' >]+)`)

func Project(snapshot *DraftSnapshot) DraftProjection {
	proj := DraftProjection{
		Subject:    snapshot.Subject,
		To:         append([]Address{}, snapshot.To...),
		Cc:         append([]Address{}, snapshot.Cc...),
		Bcc:        append([]Address{}, snapshot.Bcc...),
		ReplyTo:    append([]Address{}, snapshot.ReplyTo...),
		InReplyTo:  snapshot.InReplyTo,
		References: snapshot.References,
	}

	if part := findPart(snapshot.Body, snapshot.PrimaryTextPartID); part != nil {
		proj.BodyText = string(part.Body)
	}
	if part := findPart(snapshot.Body, snapshot.PrimaryHTMLPartID); part != nil {
		html := string(part.Body)
		proj.BodyHTMLSummary = summarizeHTML(html)
		proj.HasQuotedContent = hasQuotedContent(html)
	}

	parts := flattenParts(snapshot.Body)
	inlineCIDs := make(map[string]bool)
	for _, part := range parts {
		if part == nil || part.IsMultipart() {
			continue
		}
		if part.EncodingProblem {
			name := part.FileName()
			if name == "" {
				name = part.PartID
			}
			proj.Warnings = append(proj.Warnings,
				"part "+name+" has encoding problems; its content may be degraded (e.g. malformed base64, bad charset, or unparseable Content-Type)")
		}
		summary := PartSummary{
			PartID:      part.PartID,
			FileName:    part.FileName(),
			ContentType: part.MediaType,
			Disposition: part.ContentDisposition,
			CID:         part.ContentID,
		}
		switch {
		case strings.EqualFold(part.ContentDisposition, "attachment"):
			proj.AttachmentsSummary = append(proj.AttachmentsSummary, summary)
		case strings.EqualFold(part.ContentDisposition, "inline") || part.ContentID != "":
			proj.InlineSummary = append(proj.InlineSummary, summary)
			if part.ContentID != "" {
				inlineCIDs[strings.ToLower(part.ContentID)] = true
			}
		}
	}

	if part := findPart(snapshot.Body, snapshot.PrimaryHTMLPartID); part != nil {
		for _, cid := range extractCIDRefs(string(part.Body)) {
			if !inlineCIDs[strings.ToLower(cid)] {
				proj.Warnings = append(proj.Warnings, "missing inline MIME part for cid:"+cid)
			}
		}
	}

	return proj
}

func flattenParts(root *Part) []*Part {
	if root == nil {
		return nil
	}
	out := []*Part{root}
	for _, child := range root.Children {
		out = append(out, flattenParts(child)...)
	}
	return out
}

func extractCIDRefs(html string) []string {
	matches := cidRefRegexp.FindAllStringSubmatch(html, -1)
	if len(matches) == 0 {
		return nil
	}
	out := make([]string, 0, len(matches))
	seen := make(map[string]bool, len(matches))
	for _, match := range matches {
		cid := strings.Trim(strings.TrimSpace(match[1]), "<>")
		key := strings.ToLower(cid)
		if cid == "" || seen[key] {
			continue
		}
		seen[key] = true
		out = append(out, cid)
	}
	return out
}

// hasQuotedContent reports whether the HTML body contains a reply or
// forward quote block generated by the Lark mail composer.
// Uses regex to match an actual <div> element with the class attribute,
// avoiding false positives from plain-text or code-snippet occurrences.
func hasQuotedContent(html string) bool {
	return quoteWrapperRe.MatchString(html)
}

// splitAtQuote splits an HTML body into the user-authored content and
// the trailing reply/forward quote block. If no quote block is found,
// quote is empty and body is the original html unchanged.
func splitAtQuote(html string) (body, quote string) {
	loc := quoteWrapperRe.FindStringIndex(html)
	if loc == nil {
		return html, ""
	}
	return html[:loc[0]], html[loc[0]:]
}

func summarizeHTML(html string) string {
	trimmed := strings.TrimSpace(html)
	runes := []rune(trimmed)
	if len(runes) <= 240 {
		return trimmed
	}
	return string(runes[:240]) + "..."
}
